### ISSUE TITLE
For TheSession: The artist property of recording is not reconciled

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#174]
Even though less than 1 % is reconciled, we should reconcile as much as possible.

Some other to be reconciled:<br>

> 1. mode of tune: values of Gregorian mode
> 2. day of week of sessions

**Comment by fujinaga** [comment]
If https://thesession.org/recordings/artists/* are not automatically reconciled with OpenRefine, we should store the name(s) as a string in our RDF database. In the future (next summer), we should write a script, so that individual artists are separated and reconciled (please make this a new issue with Priority: Low). In general, we should do this for any entries when we are reconciling with OpenRefine. If we are manually reconciling, we should have a record of the manual conversion results, so that subsequent reconciliations with the same database will not need the manual conversion.

**Comment by candlecao** [comment]
Yes, I agree on that. Even if we store the names for artists as strings, I believe I can figure out a way to answer "Find in TheSession performers who is older than 60" using SPARQL. I will try it.

**Comment by candlecao** [comment]
Some reconciled samples are recorded in https://github.com/DDMAL/linkedmusic-datalake/blob/main/thesession/data/reconciled/frequently_occurring_artists_of_recordings_withReconciledWikiID.xlsx
and will be updated from time to time.
