### ISSUE TITLE
I am not sure if uploading the same triples will cause duplicated storage in Virtuoso.

### ISSUE THREAD

**Issue by candlecao** [DDMAL/linkedmusic-datalake#209]
For example, If I upload an X.ttl file which contains `<s1> <p1> <o1>`, and later upload a Y.ttl file which also includes `<s1> <p1> <o1>`, will there be a duplicate of `<s1> <p1> <o1>` in the storage?

Possibly.

So the question is whether Virtuoso can filter out duplicated triples?
I will examine it.

**Comment by ahankinson** [comment]
My understanding is that, if `<s1> <p1> and <o1>` are all the same **URI**, then it will not store duplicates, since that's how it creates the connection in the graph -- you can load two different graphs that have a few common URIs, and it will add the statement to the existing URIs.

However, if you have something like `<s1> <rdfs:label> "Foo"` and `<s1> <rdfs:label> "Foo (Bar)"`, then you have two label triples for `<s1>`.

**Comment by candlecao** [comment]
I probably have happened to upload duplicated data to my localhost Virtuoso. To have a contrast with the same dataset TheSession on staging Virtuoso:
![image](https://github.com/user-attachments/assets/6c34effe-dcca-487a-8355-34189f45597b)
![image](https://github.com/user-attachments/assets/08aae08f-8afe-4597-a944-208f5c3050fa)

**Comment by ahankinson** [comment]
You might be seeing duplicates because it cannot de-duplicate a string literal value?

**Comment by candlecao** [comment]
I have found out the reason: because I didn't specify the Default Graph IRI, it returned the same triples from different named graphs. It was an oversight on my part.
![Screenshot 2024-10-11 at 10 01 25](https://github.com/user-attachments/assets/dbe83db7-6b20-4242-a464-8bca8569eea8)
--Since I set it to <http://sample/thesession/reconciled>, the result is not duplicated any more.

Thank you!
